import { Router } from 'express'
import prisma from '../prismaClient'

const router = Router()

// Improved generate: respects subject priority, minSessionMinutes, and avoids consecutive same-subject assignments when possible.
// POST /api/plans/generate
// body: { studentId, weekStart, options?: { minSessionMinutes?: number, avoidConsecutive?: boolean } }
router.post('/generate', async (req, res) => {
  const { studentId, weekStart, options } = req.body
  if (!studentId || !weekStart) return res.status(400).json({ error: 'studentId and weekStart required' })

  const minSessionMinutes = options?.minSessionMinutes ?? 30
  const avoidConsecutive = options?.avoidConsecutive ?? true

  try {
    const weekDate = new Date(weekStart)
    const timetable = await prisma.timetable.findFirst({ where: { studentId, weekStart: weekDate }, include: { slots: true } })
    if (!timetable) return res.status(404).json({ error: 'No timetable' })

    const subjects = await prisma.subject.findMany({ where: { studentId } })
    if (!subjects || subjects.length === 0) return res.status(400).json({ error: 'No subjects' })

    const parseHM = (hm:string) => { const [hh,mm] = hm.split(':').map(Number); return hh*60 + mm }
    const formatHM = (minutes:number) => {
      const hh = Math.floor(minutes/60); const mm = minutes%60
      return `${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}`
    }

    const slots = timetable.slots
      .map(s=> ({ ...s }))
      .sort((a:any,b:any)=> a.dayOfWeek - b.dayOfWeek || parseHM(a.startTime) - parseHM(b.startTime))

    const slotDurations = slots.map((s:any)=> Math.max(0, parseHM(s.endTime) - parseHM(s.startTime)))
    const totalAvailable = slotDurations.reduce((a,b)=>a+b,0)
    if (totalAvailable <= 0) return res.status(400).json({ error: 'No available minutes in timetable' })

    // Compute weight (priority) and desired minutes per subject
    const totalTarget = subjects.reduce((sum, s) => sum + (s.weeklyTargetHours || 0), 0)
    const allocInputs = subjects.map(s => ({ id: s.id, priority: (s.priority ?? 0) + 1, targetHours: (s.weeklyTargetHours ?? 0) }))
    // If no explicit targets, distribute by priority; otherwise by targetHours weighted by priority
    let subjectDesiredMinutes: { [k:string]: number } = {}
    if (totalTarget > 0) {
      const weighted = allocInputs.map(a => ({ id: a.id, weight: a.priority * a.targetHours }))
      const weightSum = weighted.reduce((s:any, w:any)=> s + w.weight, 0) || allocInputs.length
      weighted.forEach(w => { subjectDesiredMinutes[w.id] = Math.round((w.weight/weightSum) * totalAvailable) })
    } else {
      const weightSum = allocInputs.reduce((s,a)=> s + a.priority, 0)
      allocInputs.forEach(a => { subjectDesiredMinutes[a.id] = Math.round((a.priority/weightSum) * totalAvailable) })
    }

    // Create plan and allocations
    const plan = await prisma.plan.create({ data: { studentId, weekStart: weekDate, autoGenerated: true } })
    for (const sid of Object.keys(subjectDesiredMinutes)){
      await prisma.allocation.create({ data: { planId: plan.id, subjectId: sid, hours: Math.round((subjectDesiredMinutes[sid]/60)*100)/100, sessions: 0 } })
    }

    // Distribute into slots trying to avoid consecutive same-subject
    const createdSessions:any[] = []
    let lastAssignedSubject: string | null = null
    for (let i=0;i<slots.length;i++){
      const slot = slots[i]
      let remaining = slotDurations[i]
      let cursor = parseHM(slot.startTime)

      while (remaining > 0) {
        // choose subject with most remaining minutes, prefer not-equal to lastAssignedSubject
        const candidates = Object.keys(subjectDesiredMinutes).map(id => ({ id, left: subjectDesiredMinutes[id] || 0 }))
          .filter(c => c.left > 0)
        if (candidates.length === 0) break
        candidates.sort((a,b)=> b.left - a.left)
        let pick = candidates[0].id
        if (avoidConsecutive && lastAssignedSubject && candidates.some(c=>c.id!==lastAssignedSubject)){
          const alt = candidates.find(c=>c.id !== lastAssignedSubject)
          if (alt) pick = alt.id
        }

        const left = subjectDesiredMinutes[pick]
        // determine take: try at least minSessionMinutes when possible
        let take = Math.min(remaining, left)
        if (take < minSessionMinutes && left >= minSessionMinutes && remaining >= minSessionMinutes) take = minSessionMinutes
        // if remaining slot small and take would be zero, allow small remainder
        if (take <= 0) { break }

        const dayDate = new Date(weekDate)
        dayDate.setDate(weekDate.getDate() + slot.dayOfWeek)
        const startDate = new Date(dayDate.getFullYear(), dayDate.getMonth(), dayDate.getDate(), Math.floor(cursor/60), cursor%60)

        const sess = await prisma.studySession.create({ data: {
          planId: plan.id,
          subjectId: pick,
          date: startDate,
          startTime: formatHM(cursor),
          durationMinutes: take,
          completed: false
        }})
        createdSessions.push(sess)

        subjectDesiredMinutes[pick] -= take
        remaining -= take
        cursor += take
        lastAssignedSubject = pick
      }
    }

    // Update allocation session counts and actual hours
    for (const sid of Object.keys(subjectDesiredMinutes)){
      const count = await prisma.studySession.count({ where: { planId: plan.id, subjectId: sid } })
      const minutes = await prisma.studySession.aggregate({ _sum: { durationMinutes: true }, where: { planId: plan.id, subjectId: sid } })
      const hours = ((minutes._sum.durationMinutes || 0) / 60)
      await prisma.allocation.updateMany({ where: { planId: plan.id, subjectId: sid }, data: { sessions: count, hours: Math.round(hours*100)/100 } })
    }

    const fullPlan = await prisma.plan.findUnique({ where: { id: plan.id }, include: { allocations: true, sessions: true } })
    res.json({ plan: fullPlan, createdSessions })
  } catch (err) {
    console.error(err)
    res.status(500).json({ error: 'server error' })
  }
})

export default router
